{% set name = "forte2" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evangelistalab/forte2/archive/v{{ version }}.tar.gz
  sha256: eff2f1409ae3dcecc841af34672d4879c4aa311a0c5c325416ccecb187a72272

build:
  skip: True  # [win]
  skip: True  # [py<311]
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake =3.26
    - make
    - scikit-build-core >=0.10
  host:
    - python
    - pip
    - nanobind >=1.3.2
    - cmake =3.26
    - scikit-build-core >=0.10
    - openblas
    - eigen
    - boost
    - libint
  run:
    - python
    - numpy
    - scipy
    - regex
    - basis_set_exchange
    - libint
    - libopenblas
    - pytest
    - scikit-build-core >=0.10

test:
  imports:
    - forte2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evangelistalab/forte2
  dev_url: https://github.com/evangelistalab/forte2
  doc_url: https://forte2.readthedocs.io/en/latest/
  doc_source_url: https://github.com/evangelistalab/forte2/tree/main/docs/source
  license: LGPL-3.0-only AND GPL-3.0-only
  license_file:
    - COPYING.LESSER
    - COPYING
  summary: An open-source suite of quantum chemistry methods for strongly correlated electrons
  description: |
    Forte2 is a primarily Python-based, open-source, standalone package that
    implements a variety of quantum chemistry methods for strongly correlated electrons.

extra:
  recipe-maintainers:
    - brianz98
    - fevangelista
